webödev/WebApplication6/Controllers/RolController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using WebApplication6.Models;

namespace Web_Programlama_2.Ödev.Controllers
{
    public class RolController : Controller
    {
        [Authorize]
        public class RolYonetimController : Controller
        {
            ApplicationDbContext context = new ApplicationDbContext();
            public ActionResult ChangeCulture(String lang)
            {
                if (lang != null)
                {
                    Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(lang);
                    Thread.CurrentThread.CurrentCulture = new CultureInfo(lang);
                }
                HttpCookie cookie = new HttpCookie("Language");
                cookie.Value = lang;
                Response.Cookies.Add(cookie);
                return View("Index");
            }
            // GET: RolYonetim
            public ActionResult Index()
            {
                var roleStore = new RoleStore<IdentityRole>(context);
                var roleManager = new RoleManager<IdentityRole>(roleStore);

                var model = roleManager.Roles.ToList();
                return View(model);
            }
            public ActionResult RolEkle()
            {
                return View("");
            }
            [HttpPost]
            public ActionResult RolEkle(RolEkleModel rol)
            {
                var roleStore = new RoleStore<IdentityRole>(context);
                var roleManager = new RoleManager<IdentityRole>(roleStore);
                if (roleManager.RoleExists(rol.RolAdi) == false)
                {
                    roleManager.Create(new IdentityRole(rol.RolAdi));
                }
                return RedirectToAction("Index");
            }
            public ActionResult RolKullaniciEkle()
            {
                return View();
            }
            [HttpPost]
            public ActionResult RolKullaniciEkle(RolEkleModel model)
            {
                var roleStore = new RoleStore<IdentityRole>(context);
                var roleManager = new RoleManager<IdentityRole>(roleStore);

                var userStore = new UserStore<ApplicationUser>(context);
                var userManager = new UserManager<ApplicationUser>(userStore);

                var kullanici = userManager.FindByName(model.KullaniciAdi);
                if (!userManager.IsInRole(kullanici.Id, model.RolAdi))
                {
                    userManager.AddToRole(kullanici.Id, model.RolAdi);
                }
                return RedirectToAction("Index");
            }
        }
    }
}

webödev/WebApplication6/Views/Rol/Index.cshtml
@model List<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}
<div class="row" style="text-align:center;">
    <h2>@Resource.Language.Roller</h2>
    <hr />
</div>
@Html.ActionLink(Resource.Language.RolEkle, "RolEkle") | @Html.ActionLink(Resource.Language.RolAta, "RolKullaniciEkle")
<br />
<br />
@foreach (var item in Model)
{

    <tr>
        <td>@item.Name : </td>
        <td> @item.Users.Count</td>
    </tr>

    <br />        <br />
}

webödev/WebApplication6/Views/Rol/RolEkle.cshtml
@model WebApplication6.Models.Roller
@{
    ViewBag.Title = "RolEkle";
}
<div class="row" style="text-align:center;">
    <h2>@Resource.Language.RolEkle</h2>
    <hr />
</div>
@using (Html.BeginForm("RolEkle", "RolYonetim", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Rol Adı : ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.KullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <br /><br />
    <input type="submit" value="@Resource.Language.Ekle" style="margin-left:100px;" />
}
<br /><br />

webödev/WebApplication6/Views/Rol/RolKullaniciEkle.cshtml
@model WebApplication6.Models.RolEkleModel
@{
    ViewBag.Title = "RolKullaniciEkle";
}
<div class="row" style="text-align:center;">
    <h2>@Resource.Language.RolAta</h2>
    <hr />
</div>
@using (Html.BeginForm("RolKullaniciEkle", "Rol", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kullanıcı Adı : ", htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.TextBoxFor(model => model.KullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <br />    <br />
    <div class="form-group">
        @Html.Label("Rol Adı : ", htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.TextBoxFor(model => model.KullaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
}